---
# The bare necessities.
- name: Install the essentials
  apt: name={{ item }} state=present
  with_items:
  - ctags
  - curl
  - dnsutils
  - git
  - htop
  - nmap
  - mtr
  - ranger
  - stow
  - sudo
  - tcpdump
  - tmux
  - tree
  - vim-nox
  - weechat
  - wget
  - zsh

- name: Set timezone
  shell: "{{ item }}"
  become: True
  with_items:
    - echo "US/Los_Angeles" > /etc/timezone
    - dpkg-reconfigure -f noninteractive tzdata
